# CURRENTLY OBSOLETE
cc_library(
	name = "linux-x86",
	srcs = ["core.c", "entry.S", "auxv.h"],
	hdrs = ["libsyscall.h"],
	copts = ["-nostdlib", "-nostdinc", "-m32"],
	linkopts = ["-nostdlib", "-nostdinc", "-m32"],
)
